### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Purefreeman** [drJeckyll/tumblr-chat-messages-downloader#2]
```
Fetch: login, PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php:53
Stack trace:
#0 {main}
  thrown in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 53

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php:53
Stack trace:
#0 {main}
  thrown in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 53
```

**Comment by drJeckyll** [comment]
Clearly you don't have curl extension: http://php.net/manual/en/book.curl.php

**Comment by Purefreeman** [comment]
now im just getting this error 
```
Fetch: login, PHP Notice:  Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65

Notice: Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65
home, done.

Invlid username or password!
```
My details are correct as i used it to login after getting error

**Comment by drJeckyll** [comment]
It works with my user and password. 
Did you specify -b XXX without tumblr.com?

**Comment by Purefreeman** [comment]
This what i typed into the command line
```
php tumblr.php -u xxxxxxx@hotmail.co.uk -p xxxxxxxxx -b xxxxxxx [-c conversation] [-f filename] [-s] [-d YYYYMMDD]

Fetch: login, PHP Notice:  Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65

Notice: Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65
home, done.

Invlid username or password!
```

**Comment by drJeckyll** [comment]
just this:
php tumblr.php -u xxxxxxx@hotmail.co.uk -p xxxxxxxxx -b xxxxxxx
first you need to get list of conversations, then use:
php tumblr.php -u xxxxxxx@hotmail.co.uk -p xxxxxxxxx -b xxxxxxx -c xxxxx
from the list from prev command
if you want to save msgs then add -f filename.txt & etc with other arguments. Everything with [] is optional argument.

**Comment by Purefreeman** [comment]
still the same case, i even changed my password and tried several times

```
C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master>php tumblr.php -u xxxxxxxxxxxxx@hotmail.co.uk -p xxxxxxxxxxxx -b xxxxxxxxx

Fetch: login, PHP Notice:  Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65

Notice: Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 65
home, done.

Invlid username or password!
```

**Comment by drJeckyll** [comment]
OK open the script and make these changes around 65:

echo $r; // add this line
preg_match('#<meta name="tumblr-form-key" id="tumblr_form_key" content="(.*?)">#', $r,$matches);
print_r($matches); // add this line
$key = $matches[1];

and post the result.

**Comment by Purefreeman** [comment]
```
Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master>php tumblr.php -u xxxxxxxxxxxxx@hotmail.co.uk -p xxxxxxxxxxxx -b xxxxxxxxx

Array
(
    [0] =>
)
PHP Notice:  Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 70

Notice: Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 70
home, done.

Invlid username or password!
```
![code_2018-06-29_17-17-42](https://user-images.githubusercontent.com/20708611/42103387-ce1e306c-7bc0-11e8-98f1-6fa56238b21e.png)

**Comment by drJeckyll** [comment]
nope. you need to add 
```
echo $r;
```
before line 64 (on your shot)
and 
```
print_r($matches);
```
after it

**Comment by Purefreeman** [comment]
```
Fetch: login, Array
(
)
PHP Notice:  Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 67

Notice: Undefined offset: 1 in C:\Users\dolap_000\Desktop\tumblr-chat-messages-downloader-master\tumblr.php on line 67
home, done.

Invlid username or password!

```
![code_2018-06-30_22-01-10](https://user-images.githubusercontent.com/20708611/42129051-8fff6df4-7cb1-11e8-88f4-4423a8b50122.png)

**Comment by drJeckyll** [comment]
Not sure what's wrong with it, but it looks like you don't receive login page at all. 

echo $r; must print bunch of HTML, not empty, so make sure your curl is working. May be with creating simple php script with just one curl call and see if it is working. Try the example from here: http://php.net/manual/en/function.curl-exec.php

**Comment by pienilinnunrata** [comment]
Got the same problem, curl_error said "Curl error: SSL certificate problem: unable to get local issuer certificatedone." 
Probs not the best way to fix this but if you add
`curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
curl_exec returns the page alright 
Got another error after this which is irrelevant to this one lol

**Comment by drJeckyll** [comment]
@pienilinnunrata You can check https://git.jeckyll.net/published/personal/tumblr-chat-messages-downloader with --skip-cert-verify option now to disable cert verification. BTW this repo will not be updates anymore so use new one.
